version: "3.7"
services:
    
    websocket:
        image: 'quay.io/soketi/soketi:latest-16-alpine'
        ports:
            - '6001:6001'
    
    frontend:
        build:
            context: frontend/docker/local/node
        environment:
            REACT_APP_API_URL: http://api.cbtr.qa
            REACT_APP_PUSHER_HOST: websocket
            REACT_APP_PUSHER_PORT: 6001
            REACT_APP_MAPBOX_TOKEN: pk.eyJ1IjoiYWxleGV5azg5IiwiYSI6ImNsOXNkcWtyNDB6bTMzdnA1dGs4NnRoajMifQ.JO4eOsyEmrADviQDHbTzeA
        command: sh -c "DISABLE_ESLINT_PLUGIN=true yarn build && ./node_modules/.bin/serve -s build -l 80"
        tty: true
        volumes:
            - $CI_PROJECT_DIR/frontend:/app
        hostname: frontend.cbtr.qa

    api:
        image: ${REGISTRY}/api:${IMAGE_TAG}
        depends_on:
            - api-php-fpm
        ports:
            - '8081:80'
        hostname: api.cbtr.qa
    
    api-php-fpm:
        image: ${REGISTRY}/api-php-fpm:${IMAGE_TAG}
        restart: always
        environment: &api-env
            APP_NAME: Chilled Butter App
            APP_ENV: local
            APP_KEY: base64:K3ioEHm0vVGebgA72cAhtfyncROd56YP3Rv33LjKaYc=
            APP_DEBUG: 1
            APP_URL: http://api.cbtr.qa
            APP_FRONTEND_URL: http://frontend.cbtr.qa
            APP_FRONTEND_SHORT_URL: http://frontend.cbtr.qa
            SANCTUM_STATEFUL_DOMAINS: api.cbtr.qa,frontend.cbtr.qa
            SESSION_DOMAIN: .cbtr.qa
            LOG_CHANNEL: stack
            LOG_LEVEL: debug
            DB_CONNECTION: pgsql
            DB_HOST: api-postgres-e2e
            DB_PORT: 5432
            DB_DATABASE: api
            DB_USERNAME: app
            DB_PASSWORD: password
            FILESYSTEM_DISK: s3
            AWS_ACCESS_KEY_ID: app
            AWS_SECRET_ACCESS_KEY: password
            AWS_DEFAULT_REGION: us-east-1
            AWS_BUCKET: local
            AWS_ENDPOINT: http://minio:9000
            AWS_USE_PATH_STYLE_ENDPOINT: "true"
            TWILIO_AUTH_TOKEN:
            TWILIO_ACCOUNT_SID: 
            TWILIO_API_KEY: 
            TWILIO_API_SECRET: 
            TWILIO_FROM: 
            BROADCAST_DRIVER: pusher
            PUSHER_APP_KEY: app-key
            PUSHER_APP_ID: app-id
            PUSHER_APP_SECRET: app-secret
            PUSHER_HOST: websocket
            PUSHER_PORT: 6001
            REDIS_HOST: redis
            SESSION_DRIVER: redis
            CACHE_DRIVER: redis
            QUEUE_CONNECTION: redis
            MAIL_MAILER: smtp
            MAIL_HOST: mailhog
            MAIL_PORT: 1025
            MAIL_USERNAME: null
            MAIL_PASSWORD: null
            MAIL_ENCRYPTION: "false"
            MAIL_FROM_NAME: Chilled Butter App
            MAIL_FROM_ADDRESS: noreply@admin.com
            SENTRY_LARAVEL_DSN:
            PAYPAL_MODE: sandbox
            STRIPE_KEY: pk_test_51J2vJsHo87dDYX5eAK5O1SahUq94E7vAaWEiejpXT2kmFKXRqp64NKFjc9raLeZuvPXeDEhnApKULaMtc1ufMo1n00FORfPjVQ
            STRIPE_SECRET: sk_test_51J2vJsHo87dDYX5eUfBTydJwlePBYTeJiVV8Xj70CgqqPcd6YfamxpeMUyOv24VoGiFeyuLfwRJuyvDgUHqIm4fR00OXPQfmUb
            STRIPE_WEBHOOK_SECRET: whsec_7c12437ef0226343aec4a0f790479193516825ec272564239205050e08031e7a
            AUTHNET_API_LOGIN_ID: 843wE5Qn2
            AUTHNET_TRANSACTION_KEY: 4TcDL8K58Z35su3J
            GITLAB_CI: ${GITLAB_CI}
        cap_add:
            - ALL
        privileged: true
        depends_on:
            - api-postgres-e2e

    api-php-schedule:
        image: ${REGISTRY}/api-php-cli:${IMAGE_TAG}
        command: php artisan schedule:work
        environment:
            <<: *api-env
        networks:
            - default
        depends_on:
            - redis
            - api-php-fpm

    api-php-queue:
        image: ${REGISTRY}/api-php-cli:${IMAGE_TAG}
        command: php artisan queue:work
        environment:
            <<: *api-env
        networks:
            - default
        depends_on:
            - redis
            - api-php-fpm

    api-migration:
        image: ${REGISTRY}/api-php-cli:${IMAGE_TAG}
        command: php artisan migrate:fresh --seed --seeder=EndToEndSeeder --no-interaction --force
        environment:
            <<: *api-env
        networks:
            - default
        depends_on:
            - redis
            - api-php-fpm
        
    redis:
        image: 'redis:alpine'
        ports:
            - "6379"
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            retries: 3
            timeout: 5s

    minio:
        image: 'minio/minio:latest'
        ports:
            - '9000:9000'
            - '8900:8900'
        environment:
            MINIO_ROOT_USER: 'app'
            MINIO_ROOT_PASSWORD: 'password'
        command: minio server /data/minio --console-address ":8900"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            retries: 3
            timeout: 5s

    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - "1025:1025"
            - "8025:8025"

    api-postgres-e2e:
        image: postgres:13.1-alpine
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: password
            POSTGRES_DB: api
        ports:
            - "5432:5432"

    e2e:
        build:
            context: e2e
            dockerfile: docker/Dockerfile
        environment:
            - CYPRESS_baseUrl=http://frontend.cbtr.qa
        command: sh -c "npx wait-on http://frontend.cbtr.qa -l && npx cypress run"
        volumes:
            - $CI_PROJECT_DIR/e2e/cypress:/app/cypress
            - $CI_PROJECT_DIR/e2e/cypress.config.js:/app/cypress.config.js
        tty: true
        depends_on:
            - frontend