PUT /mailboxes/1/tags/1 HTTP/1.1
Host: localhost:8081
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "label": "Test",
    "color": "#000fff",
    "icon": "😀",
    "excluded_employees": [5]
}
