---
- name: Install Certbot
  apt:
      name: certbot
      state: present
      update_cache: yes

- name: Copy certbot configuration
  copy:
      src: files/cli.ini
      dest: /etc/letsencrypt/cli.ini
      owner: root
      group: root
      mode: 0664

- name: Remove useless packages
  apt:
      autoclean: true

- name: Remove useless dependencies
  apt:
      autoremove: true
