PUT /services/7 HTTP/1.1
Host: localhost:8081
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "service_category_id": 1,
    "name": "Test service",
    "duration": 40,
    "interval": 10,
    "payment_type": "prepay",
    "price": "102.01",
    "prepay": "22.02",
    "employees": [
        1,
        2,
        3,
        4
    ],
    "locations": [
        1,
        2,
        3
    ],
    "self_book": true,
    "self_book_days": 14,
    "fixed_price": false,
    "is_attachments_enabled": true,
    "is_reschedule_enabled": true,
    "schedule": [
        {
            "id": "1",
            "enable": true
        },
        {
            "id": "2",
            "enable": true
        },
        {
            "id": "3",
            "enable": true
        },
        {
            "id": "4",
            "enable": false
        },
        {
            "id": "5",
            "enable": true
        },
        {
            "id": "6",
            "enable": true
        },
        {
            "id": "0",
            "enable": true
        }
    ]
}
