---
- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg-agent
      - python3-pip
      - virtualenv
      - python3-setuptools
    update_cache: yes

- name: Add GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add apt repository for stable version
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present
    filename: docker
    update_cache: yes

- name: Install Docker SDK for Python
  pip:
    name: docker

- name: Install Docker
  apt:
    name: docker-ce
    state: present
    update_cache: yes

- name: Add user to docker group
  user:
    name: "{{ansible_user}}"
    group: docker

- name: Download docker-compose 1.29.2
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: ~/docker-compose
    mode: '+x'

- name: Check docker-compose exists
  stat: path=~/docker-compose
  register: docker_compose

- name: Move docker-compose to /usr/local/bin/docker-compose
  command: mv ~/docker-compose /usr/local/bin/docker-compose
  when: docker_compose.stat.exists

- name: Set periodic Docker prune
  cron:
    name: docker-prune
    job: 'docker system prune -af --filter "until=$((30*24))h"'
    minute: '0'
    hour: '1'

- name: Remove useless packages
  apt:
    autoclean: yes

- name: Remove useless dependencies
  apt:
    autoremove: yes

